
FROM node:21 AS builder
WORKDIR /app
COPY . .
RUN npm install
RUN npm run build


FROM nginx:stable-alpine
RUN rm -rf /usr/share/nginx/html/*
COPY --from=builder /app/dist/frontend /usr/share/nginx/html

# For Router Angular 
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
