FROM eclipse-temurin:17 as builder
WORKDIR /app
COPY . ./
RUN ./mvnw clean package

FROM openjdk:17-jdk-alpine
WORKDIR /app
COPY --from=builder /app/target /app
EXPOSE 8080

CMD ["java", "-jar", "transference-0.0.1-SNAPSHOT.jar"]